### ISSUE TITLE
Section: Examining the Best Parameters

### ISSUE THREAD

**Issue by isobeldaley** [learn-co-curriculum/dsc-gridsearchcv-lab#1]
To calculate the mean training score, one needs to refer to the 'mean_test_score' inside the .cv_results_ dictionary.  Currently refers to 'mean_train_score', which is not a key for this dictionary.

**Comment by jessepisel** [comment]
Thanks for opening this issue @isobeldaley :wave:. It looks like it has been resolved as I am not able to replicate on my local machine. I am closing this issue at this time.
